# Generated by Django 3.2.13 on 2024-07-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20230808_1201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserTag',
        ),
    ]
